remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme

title: Jeremy Howard
description: Some basic examples of client interfaces to a computer vision API

author:
  name: Jeremy Howard
